// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Trakker.Areas.Admin.Controllers {
    public partial class AttributeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AttributeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditPriority() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditPriority);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditResolution() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditResolution);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditStatus() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditStatus);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditType() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditType);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AttributeController Actions { get { return MVC.Admin.Attribute; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Attribute";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string CreatePriority = "CreatePriority";
            public readonly string EditPriority = "EditPriority";
            public readonly string CreateResolution = "CreateResolution";
            public readonly string EditResolution = "EditResolution";
            public readonly string CreateStatus = "CreateStatus";
            public readonly string EditStatus = "EditStatus";
            public readonly string CreateType = "CreateType";
            public readonly string EditType = "EditType";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CreateEditPriorityForm = "~/Areas/Admin/Views/Attribute/CreateEditPriorityForm.ascx";
            public readonly string CreateEditResolutionForm = "~/Areas/Admin/Views/Attribute/CreateEditResolutionForm.ascx";
            public readonly string CreateEditStatusForm = "~/Areas/Admin/Views/Attribute/CreateEditStatusForm.ascx";
            public readonly string CreateEditTypeForm = "~/Areas/Admin/Views/Attribute/CreateEditTypeForm.ascx";
            public readonly string CreatePriority = "~/Areas/Admin/Views/Attribute/CreatePriority.aspx";
            public readonly string CreateResolution = "~/Areas/Admin/Views/Attribute/CreateResolution.aspx";
            public readonly string CreateStatus = "~/Areas/Admin/Views/Attribute/CreateStatus.aspx";
            public readonly string CreateType = "~/Areas/Admin/Views/Attribute/CreateType.aspx";
            public readonly string EditPriority = "~/Areas/Admin/Views/Attribute/EditPriority.aspx";
            public readonly string EditResolution = "~/Areas/Admin/Views/Attribute/EditResolution.aspx";
            public readonly string EditStatus = "~/Areas/Admin/Views/Attribute/EditStatus.aspx";
            public readonly string EditType = "~/Areas/Admin/Views/Attribute/EditType.aspx";
            public readonly string Index = "~/Areas/Admin/Views/Attribute/Index.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AttributeController: Trakker.Areas.Admin.Controllers.AttributeController {
        public T4MVC_AttributeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreatePriority() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreatePriority);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreatePriority(Trakker.Areas.Admin.Models.CreateEditPriorityModel viewData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreatePriority);
            callInfo.RouteValueDictionary.Add("viewData", viewData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPriority(int priorityId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPriority);
            callInfo.RouteValueDictionary.Add("priorityId", priorityId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPriority(int priorityId, Trakker.Areas.Admin.Models.CreateEditPriorityModel viewData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPriority);
            callInfo.RouteValueDictionary.Add("priorityId", priorityId);
            callInfo.RouteValueDictionary.Add("viewData", viewData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateResolution() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateResolution);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateResolution(Trakker.Areas.Admin.Models.CreateEditResolutionModel viewData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateResolution);
            callInfo.RouteValueDictionary.Add("viewData", viewData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditResolution(int resolutionId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditResolution);
            callInfo.RouteValueDictionary.Add("resolutionId", resolutionId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditResolution(int resolutionId, Trakker.Areas.Admin.Models.CreateEditResolutionModel viewData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditResolution);
            callInfo.RouteValueDictionary.Add("resolutionId", resolutionId);
            callInfo.RouteValueDictionary.Add("viewData", viewData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateStatus() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateStatus);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateStatus(Trakker.Areas.Admin.Models.CreateEditStatusModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateStatus);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditStatus(int statusId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditStatus);
            callInfo.RouteValueDictionary.Add("statusId", statusId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditStatus(int statusId, Trakker.Areas.Admin.Models.CreateEditStatusModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditStatus);
            callInfo.RouteValueDictionary.Add("statusId", statusId);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateType() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateType);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateType(Trakker.Areas.Admin.Models.CreateEditTypeModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateType);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditType(int typeId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditType);
            callInfo.RouteValueDictionary.Add("typeId", typeId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditType(int typeId, Trakker.Areas.Admin.Models.CreateEditTypeModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditType);
            callInfo.RouteValueDictionary.Add("typeId", typeId);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
