// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Trakker.Controllers {
    public partial class ErrorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return MVC.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string TicketNotFound = ("TicketNotFound").ToLowerInvariant();
            public readonly string PageNotFound = ("PageNotFound").ToLowerInvariant();
            public readonly string InvalidAction = ("InvalidAction").ToLowerInvariant();
            public readonly string UnexpectedError = ("UnexpectedError").ToLowerInvariant();
            public readonly string UserNotFound = ("UserNotFound").ToLowerInvariant();
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string InvalidAction = "~/Views/Error/InvalidAction.aspx";
            public readonly string PageNotFound = "~/Views/Error/PageNotFound.aspx";
            public readonly string TicketNotFound = "~/Views/Error/TicketNotFound.aspx";
            public readonly string UnexpectedError = "~/Views/Error/UnexpectedError.aspx";
            public readonly string UserNotFound = "~/Views/Error/UserNotFound.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ErrorController: Trakker.Controllers.ErrorController {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult TicketNotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TicketNotFound);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PageNotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PageNotFound);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult InvalidAction() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.InvalidAction);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UnexpectedError() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UnexpectedError);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UserNotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UserNotFound);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
