// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Trakker.Controllers {
    public partial class ProjectController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProjectController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult OverviewTab() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.OverviewTab);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RoadMapTab() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RoadMapTab);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ReleaseNotes() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ReleaseNotes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ComponentSummary() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ComponentSummary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProjectController Actions { get { return MVC.Project; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Project";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string OverviewTab = "OverviewTab";
            public readonly string RoadMapTab = "RoadMapTab";
            public readonly string ReleaseNotes = "ReleaseNotes";
            public readonly string ComponentSummary = "ComponentSummary";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string OverviewTab = "~/Views/Project/OverviewTab.cshtml";
            public readonly string ReleaseNotes = "~/Views/Project/ReleaseNotes.cshtml";
            public readonly string RoadMapTab = "~/Views/Project/RoadMapTab.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ProjectController: Trakker.Controllers.ProjectController {
        public T4MVC_ProjectController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult OverviewTab(string keyName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.OverviewTab);
            callInfo.RouteValueDictionary.Add("keyName", keyName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RoadMapTab(string keyName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RoadMapTab);
            callInfo.RouteValueDictionary.Add("keyName", keyName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ReleaseNotes(string keyName, int versionId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ReleaseNotes);
            callInfo.RouteValueDictionary.Add("keyName", keyName);
            callInfo.RouteValueDictionary.Add("versionId", versionId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ComponentSummary(string keyName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ComponentSummary);
            callInfo.RouteValueDictionary.Add("keyName", keyName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
